import React from 'react';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import {Routes, StackNames} from '../Routes';
import {directoryScreens, networkingScreens} from '../exportScreens';
import {TopTab} from './TopTab';

const Directory = createNativeStackNavigator();

const DirectoryStack = () => {
  return (
    <Directory.Navigator
      screenOptions={{
        headerShown: false,
        gestureEnabled: true,
      }}>
      <Directory.Screen
        name={Routes.DIRECTORY}
        component={directoryScreens.Directory}
      />

      <Directory.Screen
        name={Routes.INDIVIDUALCHAT}
        component={directoryScreens.IndividualChat}
      />
      <Directory.Screen
        name={Routes.GROUPCHAT}
        component={directoryScreens.GroupChat}
      />
      <Directory.Screen
        name={Routes.OPENCHAT}
        component={directoryScreens.OpenChat}
      />

      <Directory.Screen
        name={Routes.MESSAGES}
        component={directoryScreens.Messages}
      />

      <Directory.Screen
        name={Routes.PEOPLEATTENDEELIST}
        component={directoryScreens.PeopleAttendessList}
      />
      <Directory.Screen name={StackNames.TOPTABINCHAT} component={TopTab} />
      <Directory.Screen
        name={Routes.REQUESTCHAT}
        component={directoryScreens.RequestChat}
      />
      <Directory.Screen
        name={Routes.INVITATIONLIST}
        component={directoryScreens.InvitationList}
      />

      <Directory.Screen
        name={Routes.VIEWPOST}
        component={directoryScreens.ViewPost}
      />
      <Directory.Screen
        name={Routes.COMPANYPROFILE}
        component={directoryScreens.CompanyProfile}
      />
      <Directory.Screen
        name={Routes.COMPANYPOSTPAGE}
        component={directoryScreens.ComapnyPostPage}
      />
      <Directory.Screen
        name={Routes.COMPANYPRODUCTREVIEWPAGE}
        component={directoryScreens.ComapnyProductReviewsPage}
      />
      <Directory.Screen
        name={Routes.COMPANYPRODUCTREVIEWPREVIEW}
        component={directoryScreens.CompanyProductReviewPreview}
      />
      <Directory.Screen
        name={Routes.COMPANYSERVICEREVIEWPREVIEW}
        component={directoryScreens.CompanyServiceReviewPreview}
      />
      <Directory.Screen
        name={Routes.COMPANYPRODUCTLISTING}
        component={directoryScreens.ComapnyProductsListing}
      />
      <Directory.Screen
        name={Routes.COMPANYEVENTLISTINGPAGE}
        component={directoryScreens.CompanyEventListingPage}
      />
      <Directory.Screen
        name={Routes.EVENTDETAILEDPAGE}
        component={directoryScreens.EventDetails}
      />
      <Directory.Screen
        name={Routes.NOTIFICATIONS}
        component={directoryScreens.Notifications}
      />
      <Directory.Screen
        name={Routes.USERPROFILE}
        component={directoryScreens.UserProfile}
      />
      <Directory.Screen
        name={Routes.GROUPMEMBERSHIPSLIST}
        component={directoryScreens.GroupMemberShipsList}
      />
      <Directory.Screen
        name={Routes.USERPOSTPAGE}
        component={directoryScreens.UserPostPage}
      />
      <Directory.Screen
        name={Routes.CALENDEREVENTS}
        component={directoryScreens.CalenderEvents}
      />
      <Directory.Screen
        name={Routes.EVENTPEOPLELIST}
        component={directoryScreens.EventPeopleList}
      />
      <Directory.Screen
        name={Routes.CREATEEVENT}
        component={directoryScreens.CreateEvent}
      />
      <Directory.Screen
        name={Routes.CALENDARMAP}
        component={directoryScreens.CalenderMap}
      />
      <Directory.Screen
        name={Routes.STATUS_SCREEN}
        component={directoryScreens.CalenderStatusScreen}
      />
      <Directory.Screen
        name={Routes.REPORT}
        component={directoryScreens.Report}
      />
      <Directory.Screen
        name={Routes.EDITUSERPROFILE}
        component={directoryScreens.EditUserProfile}
      />
      <Directory.Screen
        name={Routes.EDITUSERINFORMATION}
        component={directoryScreens.EditUserInformation}
      />

      <Directory.Screen
        name={Routes.EDIT_ACCOMPLISHMENTS}
        component={directoryScreens.Edit_Accomplishments}
      />
      <Directory.Screen
        name={Routes.VIEW_ACCOMPLISHMENTS}
        component={directoryScreens.View_Accomplishments}
      />
      <Directory.Screen
        name={Routes.VIEW_CERTIFICATES}
        component={directoryScreens.View_Certificates}
      />
      <Directory.Screen
        name={Routes.ADD_CERTIFICATES}
        component={directoryScreens.Add_Certificates}
      />

      <Directory.Screen
        name={Routes.ADDGROUPMEMBERSHIPS}
        component={directoryScreens.AddGroupsMembership}
      />
      <Directory.Screen
        name={Routes.EDITCOMPANYPROFILE}
        component={directoryScreens.EditCompanyProfile}
      />
      <Directory.Screen
        name={Routes.EDITCOMPANYINFORMATION}
        component={directoryScreens.EditCompanyInformation}
      />
      <Directory.Screen
        name={Routes.EDITBUSSINESSDETAILS}
        component={directoryScreens.Edit_BusinessDetails}
      />
      <Directory.Screen
        name={Routes.PEOPLEREVIEWELIST}
        component={directoryScreens.PeopleReviewList}
      />
      <Directory.Screen
        name={Routes.ADDEDITCOMPANYPRODUCT}
        component={directoryScreens.AddEditProducts}
      />
      <Directory.Screen
        name={Routes.COMPANYSERVICESLISTING}
        component={directoryScreens.CompanyServicesListing}
      />
      <Directory.Screen
        name={Routes.ADDEDITSERVICES}
        component={directoryScreens.AddEditServices}
      />
      <Directory.Screen
        name={Routes.SETTINGS}
        component={directoryScreens.Settings}
      />
      <Directory.Screen
        name={Routes.PRIVACYPOLICY}
        component={directoryScreens.PrivacyPolicy}
      />
      <Directory.Screen
        name={Routes.TERMSANDCONDITIONS}
        component={directoryScreens.TermsAndConditions}
      />
      <Directory.Screen
        name={Routes.ACCOUNTPREFERENCES}
        component={directoryScreens.AccountPreferences}
      />
      <Directory.Screen
        name={Routes.RESETPASSWORD}
        component={directoryScreens.ResetPassword}
      />
      <Directory.Screen
        name={Routes.FORGETPASSWORDFROMSETTINGS}
        component={directoryScreens.ForgetPasswordSettings}
      />
      <Directory.Screen
        name={Routes.VERIFYOTPFROMSETTINGS}
        component={directoryScreens.VerifyOtpFromSettings}
      />
      <Directory.Screen
        name={Routes.NEWPASSWORDFROMSETTING}
        component={directoryScreens.NewPasswordFromSetting}
      />
      <Directory.Screen
        name={Routes.HELPCENTER}
        component={directoryScreens.HelpCenter}
      />

      <Directory.Screen
        name={Routes.ADDPOSTS}
        component={directoryScreens.AddPosts}
      />
      <Directory.Screen
        name={Routes.MEDIAPOSTSCREEN}
        component={directoryScreens.MediaPostScreens}
      />
      <Directory.Screen
        name={Routes.DOCUMENTPOSTSCREEN}
        component={directoryScreens.DocumentPostScreen}
      />
      <Directory.Screen
        name={Routes.POLLPOSTSCREEN}
        component={directoryScreens.PollPostScreen}
      />
      <Directory.Screen
        name={Routes.PRODUCTPOSTSCREEN}
        component={directoryScreens.ProductPostScreen}
      />
      <Directory.Screen
        name={Routes.EVENTPOSTSCREEN}
        component={directoryScreens.EventPostScreen}
      />
      <Directory.Screen
        name={Routes.SERVICESPOSTSCREEN}
        component={directoryScreens.ServicesPostScreen}
      />
      <Directory.Screen
        name={Routes.CELEBRATIONPOSTSCREEN}
        component={directoryScreens.CelebrationPostScreen}
      />
      <Directory.Screen
        name={Routes.ARTICLEPOSTSCREEN}
        component={directoryScreens.ArticlePostScreen}
      />
      <Directory.Screen
        name={Routes.RFPPOSTSCREEN}
        component={directoryScreens.DocumentPostScreen}
      />
    </Directory.Navigator>
  );
};
export default DirectoryStack;
