import React from 'react';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import {Routes, StackNames} from '../Routes';
import {networkingScreens} from '../exportScreens';
import {TopTab} from './TopTab';

const Netwrok = createNativeStackNavigator();

const NetworkStack = () => {
  return (
    <Netwrok.Navigator
      initialRouteName={Routes.NETWORKING}
      screenOptions={{
        headerShown: false,
        gestureEnabled: true,
      }}>
      <Netwrok.Screen
        name={Routes.NETWORKING}
        component={networkingScreens.Networking}
      />
      <Netwrok.Screen
        name={Routes.NOTIFICATIONS}
        component={networkingScreens.Notifications}
      />
      <Netwrok.Screen
        name={Routes.HELPCENTER}
        component={networkingScreens.HelpCenter}
      />
      <Netwrok.Screen
        name={Routes.INVITATIONLIST}
        component={networkingScreens.InvitationList}
      />
      <Netwrok.Screen
        name={Routes.USERPROFILE}
        component={networkingScreens.UserProfile}
      />
      <Netwrok.Screen
        name={Routes.GROUPMEMBERSHIPSLIST}
        component={networkingScreens.GroupMemberShipsList}
      />
      <Netwrok.Screen
        name={Routes.USERPOSTPAGE}
        component={networkingScreens.UserPostPage}
      />
      <Netwrok.Screen
        name={Routes.VIEWPOST}
        component={networkingScreens.ViewPost}
      />

      <Netwrok.Screen
        name={Routes.NETWORKINGLIST}
        component={networkingScreens.NetworkingList}
      />
      <Netwrok.Screen
        name={Routes.COMPANYPROFILE}
        component={networkingScreens.CompanyProfile}
      />
      <Netwrok.Screen
        name={Routes.COMPANYPOSTPAGE}
        component={networkingScreens.ComapnyPostPage}
      />
      <Netwrok.Screen
        name={Routes.COMPANYPRODUCTREVIEWPAGE}
        component={networkingScreens.ComapnyProductReviewsPage}
      />
      <Netwrok.Screen
        name={Routes.COMPANYPRODUCTREVIEWPREVIEW}
        component={networkingScreens.CompanyProductReviewPreview}
      />
      <Netwrok.Screen
        name={Routes.COMPANYSERVICEREVIEWPREVIEW}
        component={networkingScreens.CompanyServiceReviewPreview}
      />
      <Netwrok.Screen
        name={Routes.COMPANYPRODUCTLISTING}
        component={networkingScreens.ComapnyProductsListing}
      />
      <Netwrok.Screen
        name={Routes.COMPANYEVENTLISTINGPAGE}
        component={networkingScreens.CompanyEventListingPage}
      />
      <Netwrok.Screen
        name={Routes.EVENTDETAILEDPAGE}
        component={networkingScreens.EventDetails}
      />

      <Netwrok.Screen
        name={Routes.REPORT}
        component={networkingScreens.Report}
      />
      <Netwrok.Screen
        name={Routes.CALENDEREVENTS}
        component={networkingScreens.CalenderEvents}
      />
      <Netwrok.Screen
        name={Routes.EVENTPEOPLELIST}
        component={networkingScreens.EventPeopleList}
      />
      <Netwrok.Screen
        name={Routes.CREATEEVENT}
        component={networkingScreens.CreateEvent}
      />
      <Netwrok.Screen
        name={Routes.CALENDARMAP}
        component={networkingScreens.CalenderMap}
      />
      <Netwrok.Screen
        name={Routes.STATUS_SCREEN}
        component={networkingScreens.CalenderStatusScreen}
      />
      <Netwrok.Screen
        name={Routes.EDITUSERPROFILE}
        component={networkingScreens.EditUserProfile}
      />
      <Netwrok.Screen
        name={Routes.EDITUSERINFORMATION}
        component={networkingScreens.EditUserInformation}
      />

      <Netwrok.Screen
        name={Routes.EDIT_ACCOMPLISHMENTS}
        component={networkingScreens.Edit_Accomplishments}
      />
      <Netwrok.Screen
        name={Routes.VIEW_ACCOMPLISHMENTS}
        component={networkingScreens.View_Accomplishments}
      />
      <Netwrok.Screen
        name={Routes.VIEW_CERTIFICATES}
        component={networkingScreens.View_Certificates}
      />
      <Netwrok.Screen
        name={Routes.ADD_CERTIFICATES}
        component={networkingScreens.Add_Certificates}
      />

      <Netwrok.Screen
        name={Routes.ADDGROUPMEMBERSHIPS}
        component={networkingScreens.AddGroupsMembership}
      />
      <Netwrok.Screen
        name={Routes.EDITCOMPANYPROFILE}
        component={networkingScreens.EditCompanyProfile}
      />
      <Netwrok.Screen
        name={Routes.EDITCOMPANYINFORMATION}
        component={networkingScreens.EditCompanyInformation}
      />
      <Netwrok.Screen
        name={Routes.EDITBUSSINESSDETAILS}
        component={networkingScreens.Edit_BusinessDetails}
      />
      <Netwrok.Screen
        name={Routes.PEOPLEREVIEWELIST}
        component={networkingScreens.PeopleReviewList}
      />
      <Netwrok.Screen
        name={Routes.ADDEDITCOMPANYPRODUCT}
        component={networkingScreens.AddEditProducts}
      />
      <Netwrok.Screen
        name={Routes.COMPANYSERVICESLISTING}
        component={networkingScreens.CompanyServicesListing}
      />
      <Netwrok.Screen
        name={Routes.ADDEDITSERVICES}
        component={networkingScreens.AddEditServices}
      />
      <Netwrok.Screen
        name={Routes.SETTINGS}
        component={networkingScreens.Settings}
      />
      <Netwrok.Screen
        name={Routes.PRIVACYPOLICY}
        component={networkingScreens.PrivacyPolicy}
      />
      <Netwrok.Screen
        name={Routes.TERMSANDCONDITIONS}
        component={networkingScreens.TermsAndConditions}
      />
      <Netwrok.Screen
        name={Routes.ACCOUNTPREFERENCES}
        component={networkingScreens.AccountPreferences}
      />
      <Netwrok.Screen
        name={Routes.RESETPASSWORD}
        component={networkingScreens.ResetPassword}
      />
      <Netwrok.Screen
        name={Routes.FORGETPASSWORDFROMSETTINGS}
        component={networkingScreens.ForgetPasswordSettings}
      />
      <Netwrok.Screen
        name={Routes.VERIFYOTPFROMSETTINGS}
        component={networkingScreens.VerifyOtpFromSettings}
      />
      <Netwrok.Screen
        name={Routes.NEWPASSWORDFROMSETTING}
        component={networkingScreens.NewPasswordFromSetting}
      />
      <Netwrok.Screen
        name={Routes.MESSAGES}
        component={networkingScreens.Messages}
      />
      <Netwrok.Screen
        name={Routes.OPENCHAT}
        component={networkingScreens.OpenChat}
      />
      <Netwrok.Screen
        name={Routes.PEOPLEATTENDEELIST}
        component={networkingScreens.PeopleAttendessList}
      />
      <Netwrok.Screen name={StackNames.TOPTABINCHAT} component={TopTab} />
      <Netwrok.Screen
        name={Routes.REQUESTCHAT}
        component={networkingScreens.RequestChat}
      />

      <Netwrok.Screen
        name={Routes.ADDPOSTS}
        component={networkingScreens.AddPosts}
      />
      <Netwrok.Screen
        name={Routes.MEDIAPOSTSCREEN}
        component={networkingScreens.MediaPostScreens}
      />
      <Netwrok.Screen
        name={Routes.DOCUMENTPOSTSCREEN}
        component={networkingScreens.DocumentPostScreen}
      />
      <Netwrok.Screen
        name={Routes.POLLPOSTSCREEN}
        component={networkingScreens.PollPostScreen}
      />
      <Netwrok.Screen
        name={Routes.PRODUCTPOSTSCREEN}
        component={networkingScreens.ProductPostScreen}
      />
      <Netwrok.Screen
        name={Routes.EVENTPOSTSCREEN}
        component={networkingScreens.EventPostScreen}
      />
      <Netwrok.Screen
        name={Routes.SERVICESPOSTSCREEN}
        component={networkingScreens.ServicesPostScreen}
      />
      <Netwrok.Screen
        name={Routes.CELEBRATIONPOSTSCREEN}
        component={networkingScreens.CelebrationPostScreen}
      />
      <Netwrok.Screen
        name={Routes.ARTICLEPOSTSCREEN}
        component={networkingScreens.ArticlePostScreen}
      />
      <Netwrok.Screen
        name={Routes.RFPPOSTSCREEN}
        component={networkingScreens.DocumentPostScreen}
      />
    </Netwrok.Navigator>
  );
};

export default NetworkStack;
